// import type { Metadata } from "next";
"use client";
import "../globals.css";
import { store } from "../../redux/store";
import { Provider } from "react-redux";
import { Geist, Geist_Mono } from "next/font/google";
import ProductsNavbar from "@/components/products/ProductsNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ProductsNavbar />
      <Provider store={store}>{children}</Provider>
    </div>
  );
}
